### ISSUE TITLE
Crash with Picker Extended

### ISSUE THREAD

**Issue by StephanSteinert** [masterpoi/MinerPlanner#13]
![miner planer](https://cloud.githubusercontent.com/assets/14843079/26026769/1b3c4932-3802-11e7-8f77-72c045cb4b1d.png)
Hi,

if your mod is installed with Picker Extended, it crashes at clicking on the chest selection button.
Also a selected scheme is not saved so i must every time select the belts electric poles and no chest.

Greetings, Stephan aka steinio.

**Comment by masterpoi** [comment]
Fixed in 0.9.9
