### ISSUE TITLE
AAI Miner-related error when choosing a mining drill

### ISSUE THREAD

**Issue by undarl** [masterpoi/MinerPlanner#2]
When I try to select a different mining drill from the GUI I get the following error:

```
Error while running event on_gui_click (ID 1)
Unknown item "vehicle-miner-attachment".
Stack traceback:
__Miner_Planner__/control.lua:169:in function 'show_picker'
__Miner_Planner__/control.lua:218:in function 'show_miner_picker'
__Miner_Planner__/control.lua:532:in function 'remote_on_gui_click'
__Miner_Planner__/control.lua:604:in function <__Miner_Planner__/control.lua:603>
```
This is from the AAI Miner Vehicle mod, which creates invisible mining drill attachment entities to do its mining.

**Comment by masterpoi** [comment]
Can you try it with 0.9.4? I did an update in there that should have fixed this.

**Comment by undarl** [comment]
Checked, and looks good. No error, all available drills show up with no oddball extras.
