### ISSUE TITLE
0.95 No ghosts placed when clicking resource button, only deconstruction.

### ISSUE THREAD

**Issue by pobiega** [masterpoi/MinerPlanner#5]
As per the mod discussion page many users are reporting the same thing.

**Comment by masterpoi** [comment]
Apparently you need the blueprinting tech now before the game places the ghosts. I will lock the planner behind the same tech to make the relation clear. See https://github.com/masterpoi/MinerPlanner/issues/4

**Comment by masterpoi** [comment]
Fixed in 0.9.6
